// wishlist.types.js

export const WISHLIST_LOADING = "WISHLIST_LOADING";
export const GET_WISHLIST_ITEMS = "GET_WISHLIST_ITEMS";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const REMOVE_ALL_FROM_WISHLIST = "REMOVE_ALL_FROM_WISHLIST";
export const WISHLIST_ERROR = "WISHLIST_ERROR";
