// types.js
export const SET_ADDRESS = "SET_ADDRESS";
export const SUBMIT_ORDER_SUCCESS = "SUBMIT_ORDER_SUCCESS";
export const GET_ORDER_SUCCESS = "SUBMIT_ORDER_SUCCESS";
export const SUBMIT_ORDER_FAILURE = "SUBMIT_ORDER_FAILURE";
export const GET_ORDER_FAILURE = "SUBMIT_ORDER_FAILURE";
